[2024-05-18T23:57:26.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T23:57:26.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:20:00+00:00 [queued]>
[2024-05-18T23:57:26.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:20:00+00:00 [queued]>
[2024-05-18T23:57:26.412+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-18T23:57:26.521+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_and_Send_Data_to_DB> on 2024-05-18 12:20:00+00:00
[2024-05-18T23:57:26.577+0000] {standard_task_runner.py:63} INFO - Started process 174 to run task
[2024-05-18T23:57:26.687+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Real_Estate_Webscraping_ETL', 'Process_and_Send_Data_to_DB', 'scheduled__2024-05-18T12:20:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmp5ueuo2_j']
[2024-05-18T23:57:26.907+0000] {standard_task_runner.py:91} INFO - Job 392: Subtask Process_and_Send_Data_to_DB
[2024-05-18T23:57:29.729+0000] {task_command.py:426} INFO - Running <TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:20:00+00:00 [running]> on host 7879427f0394
[2024-05-18T23:57:30.226+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Real_Estate_Webscraping_ETL' AIRFLOW_CTX_TASK_ID='Process_and_Send_Data_to_DB' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T12:20:00+00:00'
[2024-05-18T23:57:30.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T23:57:30.512+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-18T23:57:30.515+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0,org.apache.kafka:kafka-clients:3.5.1,commons-logging:commons-logging:1.2 --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py
[2024-05-18T23:57:31.295+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-05-18T23:59:36.195+0000] {spark_submit.py:571} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-05-18T23:59:40.146+0000] {spark_submit.py:571} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-05-18T23:59:40.342+0000] {spark_submit.py:571} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-05-18T23:59:40.355+0000] {spark_submit.py:571} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-05-18T23:59:40.364+0000] {spark_submit.py:571} INFO - com.datastax.spark#spark-cassandra-connector_2.12 added as a dependency
[2024-05-18T23:59:40.379+0000] {spark_submit.py:571} INFO - org.apache.kafka#kafka-clients added as a dependency
[2024-05-18T23:59:40.381+0000] {spark_submit.py:571} INFO - commons-logging#commons-logging added as a dependency
[2024-05-18T23:59:40.381+0000] {spark_submit.py:571} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e60d837a-31ea-452f-98a7-932561a34e88;1.0
[2024-05-18T23:59:40.384+0000] {spark_submit.py:571} INFO - confs: [default]
[2024-05-19T00:00:42.166+0000] {spark_submit.py:571} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.1 in central
[2024-05-19T00:00:53.545+0000] {spark_submit.py:571} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1 in central
[2024-05-19T00:01:24.223+0000] {spark_submit.py:571} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2024-05-19T00:01:31.963+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-05-19T00:01:33.589+0000] {process_utils.py:132} INFO - Sending 15 to group 174. PIDs of all processes in the group: [241, 174]
[2024-05-19T00:01:33.622+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 174
[2024-05-19T00:01:33.780+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-19T00:01:33.904+0000] {spark_submit.py:697} INFO - Sending kill signal to spark-submit
[2024-05-19T00:01:34.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T00:01:39.779+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 490, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 539, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-05-19T00:01:40.281+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Real_Estate_Webscraping_ETL, task_id=Process_and_Send_Data_to_DB, run_id=scheduled__2024-05-18T12:20:00+00:00, execution_date=20240518T122000, start_date=20240518T235726, end_date=20240519T000140
[2024-05-19T00:01:41.268+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=241, status='terminated', started='23:57:29') (241) terminated with exit code None
[2024-05-19T00:01:41.311+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=174, status='terminated', exitcode=2, started='23:57:25') (174) terminated with exit code 2
[2024-05-19T00:01:41.367+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
