[2024-05-16T00:06:19.311+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-16T00:06:14.090275+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
