[2024-05-15T14:52:29.241+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T14:52:29.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T14:39:23.967960+00:00 [queued]>
[2024-05-15T14:52:29.258+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T14:39:23.967960+00:00 [queued]>
[2024-05-15T14:52:29.258+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-05-15T14:52:29.264+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_Send_Data> on 2024-05-15 14:39:23.967960+00:00
[2024-05-15T14:52:29.269+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Process_Send_Data', 'manual__2024-05-15T14:39:23.967960+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmp426i4vjv']
[2024-05-15T14:52:29.271+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T14:52:29.271+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask Process_Send_Data
[2024-05-15T14:52:29.271+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2024-05-15T14:52:29.295+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T14:39:23.967960+00:00 [running]> on host c9aa3afc371f
[2024-05-15T14:52:29.359+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Process_Send_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T14:39:23.967960+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T14:39:23.967960+00:00'
[2024-05-15T14:52:29.360+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T14:52:29.374+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-15T14:52:29.375+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py
[2024-05-15T14:52:29.474+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64//bin/java: No such file or directory
[2024-05-15T14:52:29.475+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-05-15T14:52:29.478+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T14:52:29.499+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py. Error code is: 1.
[2024-05-15T14:52:29.509+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Webscrape, task_id=Process_Send_Data, run_id=manual__2024-05-15T14:39:23.967960+00:00, execution_date=20240515T143923, start_date=20240515T145229, end_date=20240515T145229
[2024-05-15T14:52:29.517+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 111 for task Process_Send_Data (Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py. Error code is: 1.; 198)
[2024-05-15T14:52:29.533+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T14:52:29.547+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T14:52:29.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
