[2024-05-18T20:33:14.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T20:33:14.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Ingest_Data manual__2024-05-18T20:33:11.406360+00:00 [queued]>
[2024-05-18T20:33:14.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Ingest_Data manual__2024-05-18T20:33:11.406360+00:00 [queued]>
[2024-05-18T20:33:14.214+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-18T20:33:14.237+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Ingest_Data> on 2024-05-18 20:33:11.406360+00:00
[2024-05-18T20:33:14.262+0000] {standard_task_runner.py:63} INFO - Started process 1967 to run task
[2024-05-18T20:33:14.297+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Ingest_Data', 'manual__2024-05-18T20:33:11.406360+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpc3q2g6le']
[2024-05-18T20:33:14.322+0000] {standard_task_runner.py:91} INFO - Job 278: Subtask Ingest_Data
[2024-05-18T20:33:14.490+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Ingest_Data manual__2024-05-18T20:33:11.406360+00:00 [running]> on host f3c105d69d83
[2024-05-18T20:33:14.620+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Ingest_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T20:33:11.406360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T20:33:11.406360+00:00'
[2024-05-18T20:33:14.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T20:33:14.646+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.25.0.7', 9092)]>: connecting to kafka:9092 [('172.25.0.7', 9092) IPv4]
[2024-05-18T20:33:14.648+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-05-18T20:33:14.656+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.25.0.7', 9092)]>: Connection complete.
[2024-05-18T20:33:14.774+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-05-18T20:33:14.774+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-05-18T20:33:15.251+0000] {logging_mixin.py:188} INFO - Connecting to Scraping Browser...
[2024-05-18T20:33:15.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T20:33:15.821+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/main.py", line 208, in ingestion_start
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/main.py", line 205, in main
    await run(playwright, producer)
  File "/opt/airflow/dags/includes/main.py", line 95, in run
    browser = await pw.chromium.connect_over_cdp(SBR_WS_CDP)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 14239, in connect_over_cdp
    await self._impl_obj.connect_over_cdp(
  File "/home/airflow/.local/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 172, in connect_over_cdp
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 64, in send_return_as_dict
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.connect_over_cdp: WebSocket error: wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ 403 Auth Failed (customer_suspended)
Account is suspended
Call log:
<ws connecting> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/
  - <ws unexpected response> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ 403 Auth Failed (customer_suspended)
Account is suspended
  - <ws error> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ error WebSocket was closed before the connection was established
  - <ws connect error> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ WebSocket was closed before the connection was established
  - <ws disconnected> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ code=1006 reason=

[2024-05-18T20:33:15.865+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscrape, task_id=Ingest_Data, run_id=manual__2024-05-18T20:33:11.406360+00:00, execution_date=20240518T203311, start_date=20240518T203314, end_date=20240518T203315
[2024-05-18T20:33:15.898+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 278 for task Ingest_Data (BrowserType.connect_over_cdp: WebSocket error: wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ 403 Auth Failed (customer_suspended)
Account is suspended
Call log:
<ws connecting> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/
  - <ws unexpected response> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ 403 Auth Failed (customer_suspended)
Account is suspended
  - <ws error> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ error WebSocket was closed before the connection was established
  - <ws connect error> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ WebSocket was closed before the connection was established
  - <ws disconnected> wss://brd-customer-hl_aeb2e3e9-zone-scraping_browser1:w73om9g7axrj@brd.superproxy.io:9222/ code=1006 reason=
; 1967)
[2024-05-18T20:33:15.948+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T20:33:16.016+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T20:33:16.020+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
