[2024-05-15T22:58:19.454+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T22:58:19.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [queued]>
[2024-05-15T22:58:19.487+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [queued]>
[2024-05-15T22:58:19.488+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-15T22:58:19.497+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_Send_Data> on 2024-05-15 22:58:17.481506+00:00
[2024-05-15T22:58:19.521+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T22:58:19.512+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Process_Send_Data', 'manual__2024-05-15T22:58:17.481506+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpuix3ljad']
[2024-05-15T22:58:19.525+0000] {standard_task_runner.py:63} INFO - Started process 286 to run task
[2024-05-15T22:58:19.525+0000] {standard_task_runner.py:91} INFO - Job 136: Subtask Process_Send_Data
[2024-05-15T22:58:19.579+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [running]> on host bb5cab9afed7
[2024-05-15T22:58:19.689+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Process_Send_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T22:58:17.481506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T22:58:17.481506+00:00'
[2024-05-15T22:58:19.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T22:58:19.721+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-15T22:58:19.722+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py
[2024-05-15T22:58:19.862+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-17-openjdk-amd64/bin/java: No such file or directory
[2024-05-15T22:58:19.864+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-05-15T22:58:19.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T22:58:19.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py. Error code is: 1.
[2024-05-15T22:58:19.881+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscrape, task_id=Process_Send_Data, run_id=manual__2024-05-15T22:58:17.481506+00:00, execution_date=20240515T225817, start_date=20240515T225819, end_date=20240515T225819
[2024-05-15T22:58:19.888+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 136 for task Process_Send_Data (Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py. Error code is: 1.; 286)
[2024-05-15T22:58:19.919+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T22:58:19.932+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T22:58:19.933+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
