[2024-05-15T23:13:03.763+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T23:13:03.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [queued]>
[2024-05-15T23:13:03.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [queued]>
[2024-05-15T23:13:03.784+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-05-15T23:13:03.790+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_Send_Data> on 2024-05-15 22:58:17.481506+00:00
[2024-05-15T23:13:03.802+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T23:13:03.801+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Process_Send_Data', 'manual__2024-05-15T22:58:17.481506+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpyj2a1am2']
[2024-05-15T23:13:03.803+0000] {standard_task_runner.py:63} INFO - Started process 247 to run task
[2024-05-15T23:13:03.803+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask Process_Send_Data
[2024-05-15T23:13:03.855+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T22:58:17.481506+00:00 [running]> on host fb6491796190
[2024-05-15T23:13:03.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Process_Send_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T22:58:17.481506+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T22:58:17.481506+00:00'
[2024-05-15T23:13:03.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T23:13:03.944+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-15T23:13:03.945+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py
[2024-05-15T23:13:05.637+0000] {spark_submit.py:571} INFO - python3: can't open file '/includes/jobs/spark_consumer.py': [Errno 2] No such file or directory
[2024-05-15T23:13:05.653+0000] {spark_submit.py:571} INFO - 24/05/15 23:13:05 INFO ShutdownHookManager: Shutdown hook called
[2024-05-15T23:13:05.663+0000] {spark_submit.py:571} INFO - 24/05/15 23:13:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-9591b835-04d1-4b7b-90f9-249dc95e938f
[2024-05-15T23:13:05.684+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T23:13:05.725+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py. Error code is: 2.
[2024-05-15T23:13:05.732+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Webscrape, task_id=Process_Send_Data, run_id=manual__2024-05-15T22:58:17.481506+00:00, execution_date=20240515T225817, start_date=20240515T231303, end_date=20240515T231305
[2024-05-15T23:13:05.747+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task Process_Send_Data (Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode client /includes/jobs/spark_consumer.py. Error code is: 2.; 247)
[2024-05-15T23:13:05.794+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T23:13:05.818+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T23:13:05.819+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
