[2024-05-18T23:57:26.068+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T23:57:26.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:22:00+00:00 [queued]>
[2024-05-18T23:57:26.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:22:00+00:00 [queued]>
[2024-05-18T23:57:26.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-18T23:57:26.499+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_and_Send_Data_to_DB> on 2024-05-18 12:22:00+00:00
[2024-05-18T23:57:26.564+0000] {standard_task_runner.py:63} INFO - Started process 173 to run task
[2024-05-18T23:57:26.683+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Real_Estate_Webscraping_ETL', 'Process_and_Send_Data_to_DB', 'scheduled__2024-05-18T12:22:00+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpruhgr9c5']
[2024-05-18T23:57:26.788+0000] {standard_task_runner.py:91} INFO - Job 393: Subtask Process_and_Send_Data_to_DB
[2024-05-18T23:57:29.837+0000] {task_command.py:426} INFO - Running <TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:22:00+00:00 [running]> on host 7879427f0394
[2024-05-18T23:57:30.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Real_Estate_Webscraping_ETL' AIRFLOW_CTX_TASK_ID='Process_and_Send_Data_to_DB' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T12:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T12:22:00+00:00'
[2024-05-18T23:57:30.327+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T23:57:30.733+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-18T23:57:30.745+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0,org.apache.kafka:kafka-clients:3.5.1,commons-logging:commons-logging:1.2 --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py
[2024-05-18T23:57:32.021+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-05-18T23:59:35.750+0000] {spark_submit.py:571} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-05-18T23:59:40.570+0000] {spark_submit.py:571} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-05-18T23:59:40.701+0000] {spark_submit.py:571} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-05-18T23:59:40.735+0000] {spark_submit.py:571} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-05-18T23:59:40.753+0000] {spark_submit.py:571} INFO - com.datastax.spark#spark-cassandra-connector_2.12 added as a dependency
[2024-05-18T23:59:40.761+0000] {spark_submit.py:571} INFO - org.apache.kafka#kafka-clients added as a dependency
[2024-05-18T23:59:40.770+0000] {spark_submit.py:571} INFO - commons-logging#commons-logging added as a dependency
[2024-05-18T23:59:40.771+0000] {spark_submit.py:571} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0bf62fa7-5146-4cc0-a3f7-dac1068f0e6c;1.0
[2024-05-18T23:59:40.772+0000] {spark_submit.py:571} INFO - confs: [default]
[2024-05-19T00:00:32.658+0000] {spark_submit.py:571} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.1 in central
[2024-05-19T00:01:06.441+0000] {spark_submit.py:571} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1 in central
[2024-05-19T00:01:24.886+0000] {spark_submit.py:571} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2024-05-19T00:01:31.696+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-05-19T00:01:32.206+0000] {process_utils.py:132} INFO - Sending 15 to group 173. PIDs of all processes in the group: [245, 261, 173]
[2024-05-19T00:01:32.298+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 173
[2024-05-19T00:01:32.515+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-19T00:01:33.314+0000] {spark_submit.py:697} INFO - Sending kill signal to spark-submit
[2024-05-19T00:01:33.341+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T00:01:34.070+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 490, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 539, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-05-19T00:01:34.446+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=261, status='terminated', started='23:57:31') (261) terminated with exit code None
[2024-05-19T00:01:37.462+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Real_Estate_Webscraping_ETL, task_id=Process_and_Send_Data_to_DB, run_id=scheduled__2024-05-18T12:22:00+00:00, execution_date=20240518T122200, start_date=20240518T235726, end_date=20240519T000134
[2024-05-19T00:01:39.973+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=173, status='terminated', exitcode=2, started='23:57:25') (173) terminated with exit code 2
[2024-05-19T00:01:40.059+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=245, status='terminated', started='23:57:30') (245) terminated with exit code None
[2024-05-19T00:01:40.108+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2024-05-19T00:01:41.402+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
